databases:
  - name: reserveat
    databaseName: reserveat
    user: reserveat
    plan: free

services:
  - type: web
    name: reserveat
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: reserveat
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false