databases:
  - name: reserv-eat
    databaseName: reserv-eat
    user: reserv-eat

services:
  - type: web
    name: reserv-eat
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: reserv-eat
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false